### ISSUE TITLE
No web in Apple

### ISSUE THREAD

**Issue by antonio-fr** [troggy/colu-copay-wallet#2]
The web app with any web browser under iOS or MacOS is not handled properly. This only displays a blank page due to some errors at loading.

**Comment by troggy** [comment]
It wasn't worked because `Object.assign` is not available in Safari. Angular swallowed this error completely for me, so it was tricky to find.

Fixed in master here.
Fix itself: https://github.com/troggy/colu-copay-addon/commit/21137d4ac3231b21cd0afe2cd692441d554fd733#diff-ff47ad3cf0984752e5b756ecd486f460R46
